name: Merge Branch

on:
  workflow_dispatch:
    inputs:
      from_branch:
        description: 'Source branch to merge labels from'
        required: true
      to_branch:
        description: 'Destination branch to merge labels into'
        required: true
      tag_name:
        description: 'Name for the tag to be created'
        required: true

jobs:
  merge_labels_and_create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Debug Information
        run: |
          echo "FROM_BRANCH: ${{ github.event.inputs.from_branch }}"
          echo "TO_BRANCH: ${{ github.event.inputs.to_branch }}"
          echo "TAG_NAME: ${{ github.event.inputs.tag_name }}"
          git branch -a
          git fetch --all
          git branch -a
          
      - name: Merge labels
        run: |
          FROM_BRANCH=${{ github.event.inputs.from_branch }}
          TO_BRANCH=${{ github.event.inputs.to_branch }}
          git fetch origin $TO_BRANCH:$TO_BRANCH || { echo "Failed to fetch $TO_BRANCH"; exit 1; }
          git fetch origin $FROM_BRANCH:$FROM_BRANCH || { echo "Failed to fetch $FROM_BRANCH"; exit 1; }
          git checkout $TO_BRANCH || { echo "Failed to checkout $TO_BRANCH"; exit 1; }
          git merge --no-ff --no-edit $FROM_BRANCH || { echo "Failed to merge $FROM_BRANCH into $TO_BRANCH"; exit 1; }
          git push origin $TO_BRANCH || { echo "Failed to push changes to $TO_BRANCH"; exit 1; }
          
      - name: Create Tag
        run: |
          TAG_NAME=${{ github.event.inputs.tag_name }}
          COMMIT_ID=$(git rev-parse --short HEAD)
          git tag $TAG_NAME-$COMMIT_ID || { echo "Failed to create tag"; exit 1; }
          git push origin $TAG_NAME-$COMMIT_ID || { echo "Failed to push tag"; exit 1; }
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    

          
