name: Tag Old Commit
on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name'
        required: true
      tag_name:
        description: 'Tag name'
        required: true
      commit_id:
        description: 'Commit ID'
        required: false

jobs:
  create_tag_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get commit ID
        if: ${{ inputs.commit_id }}
        id: commit_id
        run: |
          git fetch origin ${{ inputs.branch_name }}
          echo "::set-output name=commit_id::$(git rev-parse origin/${{ inputs.branch_name }})"
      
      - name: Set commit ID
        if: ${{ inputs.commit_id }}
        run: echo "::set-output name=commit_id::${{ inputs.commit_id }}"
      
      - name: Show commit ID
        run: echo "Commit ID:${{ steps.commit_id.outputs.commit_id }}"
      
      - name: Create tag
        id: create_tag
        uses: actions/create-release@v1
        with:
          tag_name: ${{ inputs.tag_name }}
          commitish: ${{ steps.commit_id.outputs.commit_id }}
          # release_name: Release ${{ github.sha }}
          body: |
            This is an automated release tag created from commit ${{ steps.commit_id.outputs.commit_id }}.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
