name: Tag and Checkout

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'The commit ID to tag'
        required: true
      tag_name:
        description: 'The tag name to create'
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create a new tag
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git tag ${{ github.event.inputs.tag_name }} ${{ github.event.inputs.commit_id }}
          git push https://github-actions:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git ${{ github.event.inputs.tag_name }}

      - name: Checkout the new tag
        run: |
          git fetch --all
          git checkout tags/${{ github.event.inputs.tag_name }}
