name: TagOCommit
on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name'
        required: true

jobs:
  create_tag_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get latest commit ID
        id: commit_id
        run: echo "::set-output name=commit_id::$(git rev-parse HEAD)"
