name: TagOCommit
on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name'
        required: true
      tag_name:
        description: 'Tag name'
        required: true

jobs:
  create_tag_job:
    name: Create and push tag ${{ github.event.inputs.tag_name }} on branch ${{ github.event.inputs.branch_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      
      - name: Get latest commit ID of the specified branch
        id: commit_id
        run: |
          git fetch origin ${{ inputs.branch_name }}
          echo "::set-output name=commit_id::$(git rev-parse origin/${{ inputs.branch_name }})"
      
      - name: Show commit ID
        run: echo "Latest commit ID of branch '${{ inputs.branch_name }}':${{ steps.commit_id.outputs.commit_id }}"

      - name: Create tag
        id: create_tag
        run: |
          git tag -a ${{ inputs.tag_name }} -m "Tagging latest commit ${{ steps.latest_commit.outputs.commit_id }}"
          git push --tags
