name: TagOCommit
on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name'
        required: true
      tag_name:
        description: 'Tag name'
        required: true

jobs:
  create_tag_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get latest commit ID of the specified branch
        id: commit_id
        run: |
          git fetch origin ${{ inputs.branch_name }}
          echo "::set-output name=commit_id::$(git rev-parse origin/${{ inputs.branch_name }})"
      
      - name: Show commit ID
        run: echo "Latest commit ID of branch '${{ inputs.branch_name }}':${{ steps.commit_id.outputs.commit_id }}"

      - name: Create tag
        id: create_tag
        run: |
          git tag -a ${{ inputs.tag_name }} -m "Tagging commit ${{ steps.commit_id.outputs.commit_id }}"
          git push origin ${{ inputs.tag_name }}
